version : '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=1234567890'
      - 'POSTGRES_DB=market'

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8189:8189

